dist: trusty
sudo: required

language: python

python:
    - "3.4"
    - "3.5"

cache: pip

install:
    - sudo add-apt-repository -y ppa:lkoppel/opencv
    - sudo apt-get -q update
    - sudo apt-get install -y -q libopencv-dev
    - pip install -r requirements.txt

script:
    python -m unittest discover -b --pattern "*.py"

notifications:
    email: false
