dist: trusty
sudo: required

virtualenv:
    system_site_packages: true

language: python
python:
    - "3.3"
    - "3.4"

install:
    - sudo apt-get install -qq python3 python3-pip
    - sudo pip3 install -r requirements.txt

script:
    - python3 -m unittest discover --pattern "*.py"

notifications:
    recipients:
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
