dist: trusty
sudo: required

language: python
python:
    - "3.3"
    - "3.4"

install:
    - sudo apt-get install python3 python3-pip
    - sudo pip3 install -r requirements.txt

script:
    - python3 -m unittest discover --pattern "*.py"

notifications:
    recipients:
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
