dist: trusty
sudo: required

language: python

python:
    - "3.4"

cache: pip

install: pip install -r requirements.txt

script:
    - exit 0

# after_success:
#     - coveralls

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
